/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spacefiller_etherdream_EtherdreamDevice */

#ifndef _Included_spacefiller_etherdream_EtherdreamDevice
#define _Included_spacefiller_etherdream_EtherdreamDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     spacefiller_etherdream_EtherdreamDevice
 * Method:    lib_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_spacefiller_etherdream_EtherdreamDevice_lib_1start
  (JNIEnv *, jobject);

/*
 * Class:     spacefiller_etherdream_EtherdreamDevice
 * Method:    dac_count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_spacefiller_etherdream_EtherdreamDevice_dac_1count
  (JNIEnv *, jobject);

/*
 * Class:     spacefiller_etherdream_EtherdreamDevice
 * Method:    device_connect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_spacefiller_etherdream_EtherdreamDevice_device_1connect
  (JNIEnv *, jobject, jint);

/*
 * Class:     spacefiller_etherdream_EtherdreamDevice
 * Method:    device_ready
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_spacefiller_etherdream_EtherdreamDevice_device_1ready
  (JNIEnv *, jobject);

/*
 * Class:     spacefiller_etherdream_EtherdreamDevice
 * Method:    device_write
 * Signature: (I[Lspacefiller/ilda/IldaPoint;II)I
 */
JNIEXPORT jint JNICALL Java_spacefiller_etherdream_EtherdreamDevice_device_1write
  (JNIEnv *, jobject, jint, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
